FROM python:3.11-slim-buster


RUN pip install mlflow psycopg2-binary boto3

WORKDIR /app

# Create /app directory and set permissions
RUN mkdir -p /app && chmod -R a+rw /app


EXPOSE 5001


CMD ["mlflow", "server", \
     "--backend-store-uri", "postgresql://mlflow_user:mlflow_password@postgres/mlflow_db",\
     "--host", "0.0.0.0",\
     "--port", "5001", \
     "--serve-artifacts"]

