# Base image
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

# Enable bytecode compilation and Python optimization
ENV UV_COMPILE_BYTECODE=1
ENV PYTHONOPTIMIZE=1
ENV UV_LINK_MODE=copy

# Set Python path to include the src directory for imports
ENV PYTHONPATH="/app/src:$PYTHONPATH"


# Copy and install dependencies
COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv uv sync --frozen

# Copy application code
COPY src/api ./src/api/

# Pre-compile Python files to bytecode
RUN python -m compileall ./src/api

# Set PATH to use the virtual environment
ENV PATH="/app/.venv/bin:$PATH"

# Create non-root user and set permissions
RUN addgroup --system app && \
    adduser --system --ingroup app app && \
    chown -R app:app /app
# RUN apt-get update && apt-get install -y gcc g++ build-essential
# RUN python3 -m ensurepip --upgrade
# RUN python3 -m pip install --upgrade pip setuptools wheel

# # Now spaCy download should work
# RUN python3 -m spacy download en_core_web_sm


USER app

EXPOSE 8000

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
